---
title: "Google Data Analytics Certificate course (Capstone Project)"
author: "Marcin Dylong"
date: "21/07/2021"
output: pdf_document
---

## About and scenario

#### About

Final part of the Google Data Analytics Professional Certificate.

This is **fictional** case study, to perform many real-world tasks of a junior data analyst. In this case I am working for Bellabeat, a high-tech manufacturer of health-focused products for women, and meet different characters and team members. In order to answer the key business questions, I will follow the steps of the data analysis process: 
- ask;
- prepare;
- process;
- analyze;
- share;
- act;



#### Scenario

I am a junior data analyst working on the marketing analyst team at Bellabeat, a high-tech manufacturer of health-focused
products for women. Bellabeat is a successful small company, but they have the potential to become a larger player in the
global smart device market. Urška Sršen, cofounder and Chief Creative Officer of Bellabeat, believes that analyzing smart
device fitness data could help unlock new growth opportunities for the company. You have been asked to focus on one of
Bellabeat’s products and analyze smart device data to gain insight into how consumers are using their smart devices. The
insights I discover will then help guide marketing strategy for the company. I will present your analysis to the Bellabeat
executive team along with your high-level recommendations for Bellabeat’s marketing strategy.


## Ask

I am asked by Urška Sršen to analyze smart device usage data in order to gain insight into how consumers use non-Bellabeat smart
devices. She then wants me to select one Bellabeat product to apply these insights to in my presentation. These questions
will guide analysis:

1. What are some trends in smart device usage?
2. How could these trends apply to Bellabeat customers?
3. How could these trends help influence Bellabeat marketing strategy?

**Key stakeholders**:

- **Urška Sršen**: Bellabeat’s cofounder and Chief Creative Officer;
- **Sando Mur**: Mathematician and Bellabeat’s cofounder; key member of the Bellabeat executive team;

**How can my insights drive business decisions?**
Insights help company to better understand how customers use smart device in order to provide better user experience and improve products offered. 